services:
  - type: web
    name: Chemical Map
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python clean_data.py
      cp cleaned_final_proper.csv ./  # Ensure file is in root directory
    startCommand: gunicorn app:app --worker-class gevent --bind :${PORT} --timeout 300 --workers 1
    healthCheckPath: /health
