services:
  - type: web
    name: Chemical Map
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python clean_data.py
      ls -l cleaned_final_df.csv  # Verify exact file
    startCommand: gunicorn app:app --worker-class gevent --bind :${PORT} --timeout 300 --workers 1
    healthCheckPath: /health
